name: 'Init'
description: ''
runs:
  using: "composite"
  steps:
    - name: Check tag
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('./.github/actions/check/script.js')
          await script({github, context, core})
