name: 'Init'
description: ''
runs:
  using: "composite"
  steps:
    - name: Get commit hash
      id: commit
      shell: bash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Get commit hash 2
      id: commit2
      shell: bash
      run: git rev-parse --short HEAD

    - name: Get tag
      id: tag
      shell: bash
      run: echo "COMMIT_TAG=$(git tag --contains $COMMIT_HASH)" >> $GITHUB_ENV

    - name: Get tag 2
      id: tag2
      shell: bash
      run: git tag --contains $COMMIT_HASH

    - name: Dbg2
      id: Dbg2
      shell: bash
      run: git log

    - name: Check tag
      if: ${{ env.COMMIT_TAG == '' }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Commit has not tag')
