name: Check branch

on: workflow_dispatch

jobs:
  Build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: test
        run: echo "qqq"
      - uses: ./.github/actions/check