name: "Create release branch"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - id: get_last_release_tag
        name: Get last release tag
        run: echo "lastTag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - id: read_changelog
        name: Update change log
        run: echo "changelog=$(cat CHANGELOG.md)" >> $GITHUB_OUTPUT

      - id: get_notes_info
        name: Get notes info
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          result-encoding: string
          script: |
            const script = require('./.github/scripts/get_notes_info.js');
            return await script({
              core: core,
              changelog: '${{ steps.read_changelog.outputs.changelog }}'
            });

      - id:
        name: Echo dgb
        run:  |
          echo ${{ steps.get_last_release_tag.outputs.lastTag }}
          echo ${{ steps.get_notes_info.outputs.result.version }}
          echo ${{ steps.get_notes_info.outputs.result.notes }}