name: "Release: create drawft"

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          #fetch-tags: true

      - name: Fetch tags
        run: git fetch --tags

      - id: get_last_release_tag
        name: Get last release tag
        run: echo "lastTag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - id: fetch_commits
        name: Fetch commits
        run: git fetch --shallow-exclude=${{ steps.get_last_release_tag.outputs.lastTag }}

      - id: get_commits
        name: Get commits
        run: echo "commitList=$(git log --pretty=format:%h | paste -sd ' ')" >> $GITHUB_OUTPUT

      - id: get_pull_request_list
        name: Get pull request list
        run: echo "prList=$(gh pr list --state closed --search "${{ steps.get_commits.outputs.commitList }}" --json "number,url,title,closingIssuesReferences,mergeCommit")" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      # - name: Test
      #   run: echo ${{ steps.get_pull_request_list.outputs.prList }}

      - id: create_notes
        name: Create notes
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/commit_history.js');
            await script({core, '${{ steps.get_pull_request_list.outputs.prList }}'});

      #- uses: ./.github/actions/check