name: "Release: create drawft"

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Fetch tags
        run: git fetch --tags
      - uses: ./.github/actions/check