name: "Release: create drawft"

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      # - name: Fetch tags
      #   run: git fetch --tags

      # - id: create_notes
      #   name: Create notes
      #   uses: actions/github-script@v7
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script: |
      #       const script = require('./.github/scripts/commit_history.js');
      #       await script({core, exec});

      - id: get_last_release_tag
        name: Get last release tag
        run: echo "lastTag=$(gh release list --json tagName --limit 1 --template '{{range .}}{{.tagName}}{{end}}')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - id: fetch_commits
        name: Fetch commits
        run: git fetch --shallow-exclude=${{ steps.get_last_release_tag.outputs.lastTag }}

      - name: Qqqq
        run: git log --pretty=format:%h

      - id: get_commits
        name: Get commits
        run: echo "commitList=$(git log --pretty=format:%h | paste -sd ',')" >> $GITHUB_OUTPUT

      - name: Test
        run: echo ${{ steps.get_commits.outputs.commitList }}
      #- uses: ./.github/actions/check