name: Test

on:
  workflow_dispatch:

jobs:
  Prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
    - name: Get last vscode release
      id: vscode_last_release
      shell: bash
      run: |
        echo "vscode_version=`curl --silent https://update.code.visualstudio.com/api/releases/stable | jq -r '.[0]'`" >> $GITHUB_OUTPUT

    - name: Show version
      run: echo "${{ steps.vscode_last_release.outputs.vscode_version }}"

  Build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [Prepare]

    strategy:
      matrix:
        os: [
          windows-latest,
          macos-latest
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Show version
        run: echo "${{ steps.vscode_last_release.outputs.vscode_version }}"

  Publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [Build, Prepare]

    steps:
      - uses: actions/checkout@v4

      - name: Show version
        run: echo ${{ steps.vscode_last_release.outputs.vscode_version }}


